kind: pipeline
name: Rebase_kernel

clone:
  depth: 1

steps:
  - name: setup&kramel
    image: panchajanya1999/archlinux:latest
    environment:
      TOKEN:
        from_secret: token
      CHATID:
        from_secret: chat_id
    commands:
      - "export token=$TOKEN"
      - "export chat_id=$CHATID"
      - "bash kramel.sh"
